//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTestProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Product
    {
        public int id { get; set; }
        public string companyName { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public System.DateTime date { get; set; }
        public string keyword { get; set; }
        public string discount { get; set; }
    }
}
